#################################################
#			Makefile for kernel					#
#				 Î¢ÄÚºË´úÂë±àÒë					#
#################################################

final_obj	=	../bin/kernel.o

cpp_objs	=	
cc_objs		=	
asm_objs	=	start.s.o

sinclude ../make.inc