/*
 * vector.c
 *
 *  Created on: 2012-8-16
 *      Author: greenleaf
 */

#include "include/message.h"

const int msg_priority_table[48]	=
{
		MSG_PRIORITY(		MSG_EXCP_DE			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_DB			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_NMI		,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_BP			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_OF			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_BR			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_UD			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_NM			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_DF			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_9			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_TS			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_NP			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_SS			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_GP			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_PF			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_15			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_MF			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_AC			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_MC			,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_EXCP_XF			,MSG_PRIORITY_REALTIME)
		0,	// 20
		0,	// 21
		0,	// 22
		0,	// 23
		0,	// 24
		0,	// 25
		0,	// 26
		0,	// 27
		0,	// 28
		0,	// 29
		0,	// 30
		0,	// 31
		MSG_PRIORITY(		MSG_INTR_CLOCK				,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_INTR_KEYBOARD			,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_CASCADE			,MSG_PRIORITY_KERNEL)
		MSG_PRIORITY(		MSG_INTR_SERIAL2			,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_SERIAL1			,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_LPT2				,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_FLOPPY				,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_LPT1				,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_REALTIME_CLOCK		,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_INTR_IRQ2_REDIRECTED	,MSG_PRIORITY_KERNEL)
		MSG_PRIORITY(		MSG_INTR_IRQ10				,MSG_PRIORITY_KERNEL)
		MSG_PRIORITY(		MSG_INTR_IRQ11				,MSG_PRIORITY_KERNEL)
		MSG_PRIORITY(		MSG_INTR_MOUSE				,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_FPU				,MSG_PRIORITY_REALTIME)
		MSG_PRIORITY(		MSG_INTR_AT_WINCHESTER		,MSG_PRIORITY_DRIVER)
		MSG_PRIORITY(		MSG_INTR_IRQ15				,MSG_PRIORITY_KERNEL)
};
